spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/post-2?zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      javax.persistence.validation.mode: none

logging:
  level:
    org.hibernate:
      type.descriptor.sql.BasicBinder: DEBUG
      SQL: DEBUG
    org.springframework.orm.jpa: DEBUG
